title: 'PS-Group'
source:
destination: '_site'
url: 'http://ps-group.github.io'
github_username: ps-group
markdown: kramdown
highlighter: rouge

collections:
  opengl:
    output: true
    permalink: '/opengl/:path'
  sfml:
    output: true
    permalink: '/sfml/:path'
  packman:
    output: true
    permalink: '/packman/:path'
  compilers:
    output: true
    permalink: '/compilers/:path'
defaults:
    - scope:
        type: opengl
      values:
        layout: opengl
    - scope:
        type: sfml
      values:
        layout: sfml
    - scope:
        type: packman
      values:
        layout: sfml
    - scope:
        type: compilers
      values:
        layout: compilers
